### ISSUE TITLE
Souls can be spent on already-unlocked shouts

### ISSUE THREAD

**Issue by EnderTrekkie** [Anxietie/Minecraft-Shouts#2]
MC Version: 1.20.1
Mod Version: 2.0 (installed from Modrinth)
Mod loader: Fabric 0.92.2

I did /souls @s give 10. I then unlocked all shouts, then spent a soul to unlock one. The unlock button wasn't grayed out, so I clicked again. Another soul was spent. I spent all of the souls on the shout, and there was no apparent limit. The shout didn't seem more powerful than it would have been. This appears to be an oversight.

steps to reproduce:
1. unlock at least 1 shout
2. give yourself several souls
3. use the shouts menu to spend a soul on the shout and make it available to use
4. observe that step 3 can be done repeatedly on the same shout, with no change to the shout itself.

**Comment by Anxietie** [comment]
fixed with commit [3cfad19](https://github.com/Anxietie/Minecraft-Shouts/commit/3cfad19ec0fe0e3f15af974cd783e7470b753374)
